version: '3.8'

services:

  app:
    build:
      context: ./app
      dockerfile: docker/docker_files/Dockerfile
    platform: linux/amd64
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/code
    ports:
      - 8000:8000
    env_file:
      - ./app/.env
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  celery:
    restart: always
    build:
      context: ./app
      dockerfile: docker/docker_files/Dockerfile
    command: celery -A core worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./app:/code
    env_file:
      - ./app/.env
    depends_on:
      - redis
      - app

  beat:
    build:
      context: ./app
      dockerfile: docker/docker_files/Dockerfile
    command: celery -A core beat -l info
    volumes:
      - ./app:/code
    env_file:
      - ./app/.env
    depends_on:
      - redis
      - app

  flower:
    build:
      context: ./app
      dockerfile: docker/docker_files/Dockerfile
    command: celery -A core flower  --broker=redis://redis:6379
    ports:
      - 5555:5555
    env_file:
      - ./app/.env
    depends_on:
      - app
      - redis
      - celery

