# Generated by Django 4.1.4 on 2022-12-12 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'New'), (10, 'Engaged'), (20, 'Consented'), (30, 'Complete')])),
                ('cancelled', models.IntegerField(choices=[(0, '-'), (10, 'Not Eligible'), (20, 'Not Consented'), (30, 'Opted out'), (40, 'Not contactable')])),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='study.study')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('study', 'user'), name='unique_patient_per_study'),
        ),
    ]
