# Generated by Django 4.1.4 on 2022-12-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='cancelled',
            field=models.IntegerField(choices=[(0, '-'), (10, 'Not Eligible'), (20, 'Not Consented'), (30, 'Opted out'), (40, 'Not contactable')], default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (10, 'Engaged'), (20, 'Consented'), (30, 'Complete')], default=0),
        ),
    ]
