# Generated by Django 4.1.4 on 2022-12-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name': 'Study', 'verbose_name_plural': 'Studies'},
        ),
    ]
