# Generated by Django 4.1.4 on 2022-12-12 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the care provider.', max_length=100)),
                ('ods', models.CharField(help_text='NHS identifier for the care provider', max_length=8, unique=True)),
                ('contact', models.CharField(help_text='Full name and salutation of the main contact at the care provider.', max_length=50)),
            ],
        ),
    ]
