# Generated by Django 4.1.4 on 2022-12-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careprovider',
            options={'verbose_name': 'Care Provider', 'verbose_name_plural': 'Care Providers'},
        ),
    ]
